# Generated by Django 4.2.4 on 2023-09-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dewscription',
            new_name='description',
        ),
    ]
